### ISSUE TITLE
Notes: Aug 10 MVP definition call

### ISSUE THREAD

**Issue by lehnberg** [vault713/grinbox#3]
## Meeting details
* Friday 10 Aug @ 8:00 UTC
* Conference call via https://appear.in/grinbox
* Attendance
  - @ravidio 
  - @lehnberg

## Agenda
Define scope for Grinbox phases, determine immediate next steps, and actions.

## Grinbox purpose
Grinbox facilitates asynchronous Grin transaction building between multiple parties. The protocol through which this is being realised should remain open, secure, and private. It should be decentralised to the degree that is necessary in order to effectively fulfil the other objectives. We envision a future where multiple wallet and payment products and services are built that integrate with the grinbox protocol.  

## Phases

| # | Description | Details | Deliverable |
|---|---|---|---|
| **1** | **Relay service** | <ul><li>Server relay service only <li>No client <li>Publish authentication and relay APIs (public/private key based) <li> VPS hosted</ul> | Users can manually use the relay to send/receive transaction slates to/from other users. Actual transaction building and broadcasting to blockchain is done through the default grin node and wallet locally.|
|**2**| **Grinbox client** | <ul><li> A simple client accessing the grinbox account/relay and processes slates on behalf of the user. <li> Either as standalone, or through integration into the default grin wallet.</ul>| Users can more easily utilize the grinbox relay (without manual steps).|
|**3/4<br>(tbd)**| **Grin blockchain support** | <ul><li>Grin nodes running through the Grinbox relay service that supports sending and confirming transactions on the user's behalf.</ul> | Thin wallet client support.|
|**3/4<br>(tbd)**| **Federation** | <ul><li>Open the network up to allow for decentralisation and resilience. <li>Allow anyone to host a Grinbox relay server <li>Allow Grinbox relays to communicate between themselves</ul> | No single central point of failure for Grinbox.|
|**?**| **Full decentralisation** | <ul><li>Only if there is a strong justification, i.e. in event of domain name seizures or relay servers being shut down. <li>Remove dependency on domain names <li>Remove dependency on central servers<li>Migrate the network to communicate via grinbox clients directly.<li>Similar setup as magnet links for Bittorrent.</ul>| Grinbox cannot be shut down without every single client going offline.|

## Agreed next steps
- [X] @ravidio to define and publish APIs
- [X] @lehnberg to set up VPS access to ravidio for the initial relay service instance
- [X] @ravidio to set up first Grinbox relay

**Aim for this to be completed in next week.**

**Comment by gavinmcdermott** [comment]
@lehnberg @ravidio - This is great. Would you guys like to get together to talk about how we could integrate your relay into the initial wallet client we're building. 

It seems you are focused on knocking out the APIs and initial relay this week. On our end we're tackling the initial UX/UI for the user-friendly client. Perhaps we use the next 2 weeks and design+build with your relay in mind—getting everyone to a full circle test as quickly as possible. Thoughts?

cc: @jamaalm
