### ISSUE TITLE
Enable federated servers to relay all their user communication 

### ISSUE THREAD

**Issue by lehnberg** [vault713/grinbox#8]
As a user connecting to a federated grinbox server, I want all my grinbox communication to be relayed by this server, so that only the federated grinbox server I choose to trust has my IP:

```
UserA <---> Federated Relay X <--------> Federated Relay Y <---> UserB
```

**Comment by ravidio** [comment]
The issue with the proposed approach is the challenge used to sign the encrypted message. The challenge is retrieved from a specific relay, and the relay will reject a signed slate with the wrong challenge. I.e. UserA signs the slate with the challenge of Relay X, and so when X federates the slate to Y it would be rejected.

Do we have any way to fix that? One way could be to unify challenge across the federation - for instance by using an external challenge such as grin block hash or something similar.

@jaspervdm @lehnberg any ideas?

**Comment by lehnberg** [comment]
Fixed.
